language: node_js
node_js:
- lts/*
cache: yarn
before_script:
- yarn install
script:
- yarn run lint
- yarn test
- yarn run coverage
deploy:
  provider: npm
  email: 
    secure: Mtw+JfM17ltBzRXhiCx4t0Cu9Oalw8/xQ4GAVxlpra5ed4irPx6Mk6/nCr9SKXGVcsnR0bLGcdLS8divzPHFMBd11jEv7BCxijo/ir5cz31ijqoMrbs2q8hHNvKslH23+Vxt+7kvBcfXIz6k46HxgiHMSunJaI7OS5RBnV2wIFmhKRbBPBaHpEC12lX3XiMJuXBPkM8VSN5k74D05R4p3zp2gkHO86QYeSQM7XZBwXQ1t2dc74K59MtnP8h86DXUNZgR9OPdHZbqEpOdYiKnauaejndxDG/7txDRUjtDxsQk2zBQSBVcNYumM8lyFS1hTSMkwoSJyef/YRRFlytTIq6k8CwDKogiCIU4ZL2fHWzmrioy6e7pGi7ODguWp+nB9goZhtrOLvmsaoFJv4i62m+B70cwT2a8vszwaSOjtjvukctA1PKrET08x4GzIifpGEUBwVGBXioUvm/NBKgBSsGlo9/E6AO/+u8MRgYaKa+1h7xTiAiIgNM1lJIlCuyu5g09xEPWKQNWhSGuktmCMPkXtjWE83ccv/HKOlMF9HS14nDIGzAtgr44UIpX13DaccSL+V0RAelek25Dp4t5LjMicnw9IDpeyCy21bflVc/GU7XpO71UgsmudwvKxQgIHGbrTwENV6eTUSbd9cSVGdTBiZaNnnB+5Y36zswuVVY=
  api_key:
    secure: N+HqEKoJ/9Dc6M6554ZtM8LuPGms++jC0KvykA0GJyVAOmpzdmDlvODdnzfoMQEJfyS0YeL/x9hoWJoEUad2/AlDOyLn+ltd+0y8TLOMgsdwP1KPLGrR07YMgwJZzTDaIEsIAoriuaZp1zXnb7ZFGjSaHgwCUbM5GoRD6+3B42MnrWDxmjvf9aos9ojtN5G5ZTRtnJemcA5Jc8Eeg7KIGgy8nKF6dQHPdTc5oiVp/3UmIMnrZlTrKP4szh6ZZSqj+L818ZSrP4TyhX7OuBz8lLbRImIqOCrBBVA1tGpTcL6zcebxIIE5JnwS4u8RzGDYpqzQqp6P6orllwf+9kLFkYZ8Ou7ezswLuhtTX6XnLjDDlKdJtg7dIyVZGAt1NtnP7VEmJCGh7v1+B24u62128IEYWYyzKeDpY0yWcq+WRmNncDaPPZAwfIGiLclH9923Kb2rhe1GG9hNieWJKJpxLg8vOs/02ouaZhq6rsb5qb11I+q4u7YAEzDBk7qj2N9rEEDdFgqW/PnkltMp5pxoU5OY2NoC79s4U1BdueT2dFrlpfHr6i60Vff2ttq30uZyRi51vTQhEb0/soXvifN8O2sR+qVgrIYn7JYQUTp1Js7KVtl0Dihwa0ohfDxmH2wMpWfThZZwONSwRwsMxvtJxLwf8HYfi3BxWz+91bZ7lgM=
  on:
    branch: master
    tags: true
